#!/system/bin/sh
#Overclocking
#Unload OC module to 1.2GHz

rmmod cpufreq_stats
rmmod semaphore_oc
sleep 1
insmod /lib/modules/cpufreq_stats.ko

echo 1000000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# values in mV, from 1.2GHz/1GHz - 100 MHz
#echo "0 25 50 50 75" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
