#!/system/bin/sh
#Deadline
#Unload deadline I/O scheduler module

echo noop > /sys/class/block/mmcblk0/queue/scheduler
echo noop > /sys/class/block/mmcblk1/queue/scheduler
echo noop > /sys/class/block/stl10/queue/scheduler
echo noop > /sys/class/block/stl9/queue/scheduler

rmmod deadline_iosched
