#!/system/bin/sh
#Conservative
#Load conservative governor module

insmod /lib/modules/cpufreq_conservative.ko

echo conservative >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 10 >/sys/devices/system/cpu/cpu0/cpufreq/conservative/freq_step
echo 40 >/sys/devices/system/cpu/cpu0/cpufreq/conservative/down_threshold
echo 90 >/sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold
echo 0 >/sys/devices/system/cpu/cpu0/cpufreq/conservative/ignore_nice_load
