#!/system/bin/sh
#Deadline
#Load deadline I/O scheduler module

insmod /lib/modules/deadline-iosched.ko

echo deadline > /sys/class/block/mmcblk0/queue/scheduler
echo deadline > /sys/class/block/mmcblk1/queue/scheduler
echo deadline > /sys/class/block/stl10/queue/scheduler
echo deadline > /sys/class/block/stl9/queue/scheduler
echo 8 > /sys/class/block/mmcblk0/queue/iosched/fifo_batch
echo 8 > /sys/class/block/mmcblk1/queue/iosched/fifo_batch
echo 8 > /sys/class/block/stl10/queue/iosched/fifo_batch
echo 8 > /sys/class/block/stl9/queue/iosched/fifo_batch
echo 400 > /sys/class/block/mmcblk0/queue/iosched/read_expire
echo 400 > /sys/class/block/mmcblk1/queue/iosched/read_expire
echo 400 > /sys/class/block/stl10/queue/iosched/read_expire
echo 400 > /sys/class/block/stl9/queue/iosched/read_expire
echo 4 > /sys/class/block/mmcblk0/queue/iosched/writes_starved
echo 4 > /sys/class/block/mmcblk1/queue/iosched/writes_starved
echo 4 > /sys/class/block/stl10/queue/iosched/writes_starved
echo 4 > /sys/class/block/stl9/queue/iosched/writes_starved
