#!/system/bin/sh
#Governors
#Change CPU governor
#Ondemand*

echo ondemand >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

sleep 1
rmmod cpufreq_conservative
#Causes reboot on turning screen off.
#rmmod cpufreq_smartass2
