#!/system/bin/sh
#Low Memory Killer
#Minimum free memory
#80MB(Game)

setprop ro.FOREGROUND_APP_ADJ 0
setprop ro.VISIBLE_APP_ADJ 1
setprop ro.PERCEPTIBLE_APP_ADJ 1
setprop ro.HEAVY_WEIGHT_APP_ADJ 2
setprop ro.SECONDARY_SERVER_ADJ 2
setprop ro.BACKUP_APP_ADJ 2
setprop ro.HOME_APP_ADJ 4
setprop ro.HIDDEN_APP_MIN_ADJ 7
setprop ro.CONTENT_PROVIDER_ADJ 14
setprop ro.EMPTY_APP_ADJ 15

setprop ro.FOREGROUND_APP_MEM 1536
setprop ro.VISIBLE_APP_MEM 2560
setprop ro.PERCEPTIBLE_APP_MEM 5632
setprop ro.HEAVY_WEIGHT_APP_MEM 5632
setprop ro.SECONDARY_SERVER_MEM 5632
setprop ro.BACKUP_APP_MEM 5632
setprop ro.HOME_APP_MEM 2560
setprop ro.HIDDEN_APP_MEM 8192
setprop ro.CONTENT_PROVIDER_MEM 17408
setprop ro.EMPTY_APP_MEM 20480

echo "0,1,2,7,14,15" > /sys/module/lowmemorykiller/parameters/adj
echo "1536,2560,5632,8192,17408,20480" > /sys/module/lowmemorykiller/parameters/minfree
