#!/system/bin/sh
#Low Memory Killer
#Minimum free memory
#64MB(BigMem)

setprop ro.FOREGROUND_APP_ADJ 0
setprop ro.VISIBLE_APP_ADJ 1
setprop ro.PERCEPTIBLE_APP_ADJ 1
setprop ro.HEAVY_WEIGHT_APP_ADJ 2
setprop ro.SECONDARY_SERVER_ADJ 2
setprop ro.BACKUP_APP_ADJ 2
setprop ro.HOME_APP_ADJ 4
setprop ro.HIDDEN_APP_MIN_ADJ 7
setprop ro.CONTENT_PROVIDER_ADJ 14
setprop ro.EMPTY_APP_ADJ 15

setprop ro.FOREGROUND_APP_MEM 1280
setprop ro.VISIBLE_APP_MEM 2304
setprop ro.PERCEPTIBLE_APP_MEM 5120
setprop ro.HEAVY_WEIGHT_APP_MEM 5120
setprop ro.SECONDARY_SERVER_MEM 5120
setprop ro.BACKUP_APP_MEM 5120
setprop ro.HOME_APP_MEM 2304
setprop ro.HIDDEN_APP_MEM 7168
setprop ro.CONTENT_PROVIDER_MEM 14336
setprop ro.EMPTY_APP_MEM 16384

echo "0,1,2,7,14,15" > /sys/module/lowmemorykiller/parameters/adj
echo "1280,2304,5120,7168,14336,16384" > /sys/module/lowmemorykiller/parameters/minfree
