#!/system/bin/sh
#Low Memory Killer
#Minimum free memory
#32MB(Multitasking)

setprop ro.FOREGROUND_APP_ADJ 0
setprop ro.VISIBLE_APP_ADJ 1
setprop ro.PERCEPTIBLE_APP_ADJ 1
setprop ro.HEAVY_WEIGHT_APP_ADJ 2
setprop ro.SECONDARY_SERVER_ADJ 2
setprop ro.BACKUP_APP_ADJ 2
setprop ro.HOME_APP_ADJ 4
setprop ro.HIDDEN_APP_MIN_ADJ 7
setprop ro.CONTENT_PROVIDER_ADJ 14
setprop ro.EMPTY_APP_ADJ 15

setprop ro.FOREGROUND_APP_MEM 1024
setprop ro.VISIBLE_APP_MEM 2048
setprop ro.PERCEPTIBLE_APP_MEM 4096
setprop ro.HEAVY_WEIGHT_APP_MEM 4096
setprop ro.SECONDARY_SERVER_MEM 4096
setprop ro.BACKUP_APP_MEM 4096
setprop ro.HOME_APP_MEM 2048
setprop ro.HIDDEN_APP_MEM 5120
setprop ro.CONTENT_PROVIDER_MEM 7168
setprop ro.EMPTY_APP_MEM 8192

echo "0,1,2,7,14,15" > /sys/module/lowmemorykiller/parameters/adj
echo "1024,2048,4096,5120,7168,8192" > /sys/module/lowmemorykiller/parameters/minfree
