#!/system/bin/sh
#Touchscreen
#Configure touchscreen sensitivity
#Stock(Default)

echo 7040 > /sys/class/touch/switch/set_touchscreen
echo 8002 > /sys/class/touch/switch/set_touchscreen
echo 11003 > /sys/class/touch/switch/set_touchscreen
echo 13046 > /sys/class/touch/switch/set_touchscreen
echo 14005 > /sys/class/touch/switch/set_touchscreen
