#!/system/bin/sh
#VM Dirtyness
#Tunes I/O buffering (Chainfire)

echo "500" > /proc/sys/vm/dirty_writeback_centisecs
echo "200" > /proc/sys/vm/dirty_expire_centisecs
echo "20" > /proc/sys/vm/dirty_ratio
echo "5" > /proc/sys/vm/dirty_background_ratio
echo "100" > /proc/sys/vm/vfs_cache_pressure
echo "60" > /proc/sys/vm/swappiness
