#!/system/bin/sh
#Governors
#Change CPU governor
#SmartassV2

insmod /lib/modules/cpufreq_smartass2.ko

echo smartassV2 >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

sleep 1
rmmod cpufreq_conservative
