#!/sbin/ext/busybox sh

echo $0 $* >> /dev/null

if [ -f /sbin/recovery-is-running ];
then
    if echo "$*" | grep -q -i "remount";
    then
        REMOUNT=",remount";
    else
        REMOUNT="";
    fi;

    if (echo "$*" | grep -q -i "/system"); then
        busybox mount -t rfs -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/stl9 /system >> /dev/null 2>&1
        busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT /dev/block/stl9 /system >> /dev/null 2>&1
        echo busybox mount -t XXX -o rw$REMOUNT /dev/block/stl9 /system >> /dev/null
    elif (echo "$*" | grep -q -i "/datadata") || (echo "$*" | grep -q -i "/dbdata"); then
        busybox mount -t rfs -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/stl10 /datadata >> /dev/null 2>&1
        busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=0,nodelalloc$REMOUNT /dev/block/stl10 /datadata >> /dev/null 2>&1
        echo busybox mount -t XXX -o rw$REMOUNT /dev/block/stl10 /datadata >> /dev/null
        busybox mount -t rfs -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/stl10 /dbdata >> /dev/null 2>&1
        busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=0,nodelalloc$REMOUNT /dev/block/stl10 /dbdata >> /dev/null 2>&1
        echo busybox mount -t XXX -o rw$REMOUNT /dev/block/stl10 /dbdata >> /dev/null
    elif (echo "$*" | grep -q -i "/data"); then
        busybox mount -t rfs -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/mmcblk0p2 /data >> /dev/null 2>&1
        busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT /dev/block/mmcblk0p2 /data >> /dev/null 2>&1
        echo busybox mount -t XXX -o rw$REMOUNT /dev/block/mmcblk0p2 /data >> /dev/null
    elif (echo "$*" | grep -q -i "/cache"); then
        busybox mount -t rfs -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/stl11 /cache >> /dev/null 2>&1
        busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT /dev/block/stl11 /cache >> /dev/null 2>&1
        echo busybox mount -t XXX -o rw$REMOUNT /dev/block/stl11 /cache >> /dev/null
    else
	busybox mount $*
	echo busybox mount $* >> /dev/null
    fi;
else
    busybox mount $*
    echo busybox mount $* >> /dev/null
fi;
