#!/system/bin/sh
#Startup/Shutdown Sound
#Restore sounds

if busybox [ -f /system/etc/PowerOn.snd ];
then
	busybox mount -o remount,rw  /system
	cp /system/etc/PowerOn.snd /data/local/PowerOn.snd
	rm -f /system/etc/PowerOn.snd
	busybox mount -o remount,ro  /system
fi;

if busybox [ -f /system/etc/PowerOn.wav ];
then
	busybox mount -o remount,rw  /system
	cp /system/etc/PowerOn.wav /data/local/PowerOn.wav
	rm -f /system/etc/PowerOn.wav
	busybox mount -o remount,ro  /system
fi;

if busybox [ -f /system/media/audio/ui/PowerOff.wav ];
then
	busybox mount -o remount,rw  /system
	cp /system/media/audio/ui/PowerOff.wav /data/local/PowerOff.wav
	rm -f /system/media/audio/ui/PowerOff.wav
	busybox mount -o remount,ro  /system
fi;
