#!/system/bin/sh
#Profiles
#Configure Settings Profile
#Recommended(HM)

#Execute and copy scripts
mkdir /data/SemaphoreScripts
rm -f /data/SemaphoreScripts/*

#Try kernel scripts first
# SaveBattery kernel features
cp /res/scripts/S05enable_oc_1000_default /data/SemaphoreScripts
cp /res/scripts/S10enable_gov_ondemand_default /data/SemaphoreScripts
cp /res/scripts/S15enable_sched_sio /data/SemaphoreScripts
cp /res/scripts/S20disable_netfilter /data/SemaphoreScripts
cp /res/scripts/S25enable_sm_neutral /data/SemaphoreScripts
cp /res/scripts/S30disable_logger /data/SemaphoreScripts
cp /res/scripts/S35disable_tun /data/SemaphoreScripts
cp /res/scripts/S40disable_cifs /data/SemaphoreScripts
# SaveBattery addons
cp /res/scripts/addons/S60disable_cache_50 /data/SemaphoreScripts
cp /res/scripts/addons/S62disable_ipv6_privacy /data/SemaphoreScripts
cp /res/scripts/addons/S70enable_kernel_sched /data/SemaphoreScripts
cp /res/scripts/addons/S72enable_vmdirty /data/SemaphoreScripts
cp /res/scripts/addons/S74enable_lmk_64mb /data/SemaphoreScripts
cp /res/scripts/addons/S76enable_sdcard_0256kb /data/SemaphoreScripts
cp /res/scripts/addons/S78enable_touchscreen_1 /data/SemaphoreScripts

#Try sdcard second
# SaveBattery kernel features
cp /mnt/sdcard/SemaphoreScripts/S05enable_oc_1000_default /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S10enable_gov_ondemand_default /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S15enable_sched_sio /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S20disable_netfilter /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S25enable_sm_neutral /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S30disable_logger /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S35disable_tun /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S40disable_cifs /data/SemaphoreScripts
# SaveBattery addons
cp /mnt/sdcard/SemaphoreScripts/S60disable_cache_50 /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S62disable_ipv6_privacy /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S70enable_kernel_sched /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S72enable_vmdirty /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S74enable_lmk_64mb /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S76enable_sdcard_0256kb /data/SemaphoreScripts
cp /mnt/sdcard/SemaphoreScripts/S78enable_touchscreen_1 /data/SemaphoreScripts

chmod 755 /data/SemaphoreScripts/*

busybox run-parts /data/SemaphoreScripts

rm -f /data/SemaphoreScripts/*disable*
rm -f /data/SemaphoreScripts/*enable*default*
rm -f /data/SemaphoreScripts/*enable*neutral*
rm -f /data/SemaphoreScripts/*enable*standard*

# Clean and configure init.d
busybox mount -o remount,rw  /system

rm -f /system/etc/init.d/*enable*

cp /data/SemaphoreScripts/* /system/etc/init.d

busybox mount -o remount,ro  /system

rm -rf /data/SemaphoreScripts
