#!/system/bin/sh
#Kernel Scheduler
#Tweak kernel scheduler (Chainfire)

echo "18000000" > /proc/sys/kernel/sched_latency_ns
echo "3000000" > /proc/sys/kernel/sched_wakeup_granularity_ns
echo "1500000" > /proc/sys/kernel/sched_min_granularity_ns
