#!/system/bin/sh
#Startup/Shutdown Sound
#Restores files if they are backuped by the kernel

if busybox [ ! -f /system/etc/PowerOn.snd ];
then
	busybox mount -o remount,rw  /system
	cp /data/local/PowerOn.snd /system/etc/PowerOn.snd
	busybox mount -o remount,ro  /system
fi;

if busybox [ ! -f /system/etc/PowerOn.wav ];
then
	busybox mount -o remount,rw  /system
	cp /data/local/PowerOn.wav /system/etc/PowerOn.wav
	busybox mount -o remount,ro  /system
fi;

if busybox [ ! -f /system/media/audio/ui/PowerOff.wav ];
then
	busybox mount -o remount,rw  /system
	cp /data/local/PowerOff.wav /system/media/audio/ui/PowerOff.wav
	busybox mount -o remount,ro  /system
fi;
