#!/system/bin/sh
#Kernel Scheduler
#Tweak kernel scheduler (Chainfire)

echo "10000000" > /proc/sys/kernel/sched_latency_ns
echo "2000000" > /proc/sys/kernel/sched_wakeup_granularity_ns
echo "2000000" > /proc/sys/kernel/sched_min_granularity_ns
