#!/system/bin/sh
#Voodoo Color Settings
#Sets color profile to phone
#Darker-Alt.Gamma

bluemultiplier="1922509280";
greenmultiplier="1544143040";
redmultiplier="1462334080";
bluev1offset="-18";
greenv1offset="-17";
redv1offset="-14";
activeprofile="0";

# Active Profile
echo $activeprofile > /sys/class/misc/voodoo_color/active_profile

# Reset RGB Multipliers
echo $bluemultiplier > /sys/class/misc/voodoo_color/blue_multiplier
echo $greenmultiplier > /sys/class/misc/voodoo_color/green_multiplier
echo $redmultiplier > /sys/class/misc/voodoo_color/red_multiplier

# Reset Gamma Hack
echo $bluev1offset > /sys/class/misc/voodoo_color/blue_v1_offset
echo $greenv1offset > /sys/class/misc/voodoo_color/green_v1_offset
echo $redv1offset > /sys/class/misc/voodoo_color/red_v1_offset

# Reset Voodoo Control App Data
echo "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>" > /data/color_settings.xml
echo '<map>' >> /data/color_settings.xml
echo '<string name="green_multiplier">'$greenmultiplier'</string>' >> /data/color_settings.xml
echo '<string name="green_v1_offset">'$greenv1offset'</string>' >> /data/color_settings.xml
echo '<string name="red_multiplier">'$redmultiplier'</string>' >> /data/color_settings.xml
echo '<string name="active_profile">'$activeprofile'</string>' >> /data/color_settings.xml
echo '<string name="blue_v1_offset">'$bluev1offset'</string>' >> /data/color_settings.xml
echo '<string name="blue_multiplier">'$bluemultiplier'</string>' >> /data/color_settings.xml
echo '<string name="red_v1_offset">'$redv1offset'</string>' >> /data/color_settings.xml
echo '</map>' >> /data/color_settings.xml

cat /data/color_settings.xml > /dbdata/databases/org.projectvoodoo.controlapp/shared_prefs/color_settings.xml
rm -f /data/color_settings.xml
