#!/system/bin/sh
#Netfilter
#Unload netfilter modules (tethering, firewall)

rmmod nf_conntrack_ipv6
rmmod ip6t_ipv6header
rmmod ip6t_REJECT
rmmod ip6t_LOG
rmmod ip6_tables

rmmod xt_multiport
rmmod ipt_REDIRECT
rmmod xt_owner
rmmod xt_NFLOG
rmmod xt_state
rmmod xt_conntrack
rmmod ipt_MASQUERADE
rmmod iptable_nat
rmmod iptable_mangle
rmmod iptable_filter
rmmod ipt_REJECT
rmmod ipt_LOG
rmmod ip_tables
rmmod xt_TCPMSS
rmmod xt_mark
rmmod xt_policy
rmmod xt_tcpudp
rmmod x_tables

rmmod nf_conntrack_netlink
rmmod nfnetlink_log
rmmod nfnetlink
rmmod nf_nat_sip
rmmod nf_nat_irc
rmmod nf_nat_ftp
rmmod nf_nat
rmmod nf_conntrack_ipv4
rmmod nf_defrag_ipv4
rmmod nf_conntrack_sip
rmmod nf_conntrack_irc
rmmod nf_conntrack_ftp
rmmod nf_conntrack


