#!/system/bin/sh
#Disable Bootloop detection
#Disable cleaning init.d after bootloop

if /sbin/ext/busybox [ -f /system/cfroot/disable_bl ];
then
	busybox mount -o remount,rw  /system

	rm /system/cfroot/disable_bl

	busybox mount -o remount,ro  /system
fi;
